version: "3.3"
services:
  urlshortener:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
  webserver:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - urlshortener
